StrawberryHub/Models/Article.cs
using System;
using System.Collections.Generic;

namespace StrawberryHub.Models;

public partial class Article
{
    public int ArticleId { get; set; }

    public int? GoalTypeId { get; set; }

    public string ArticleContent { get; set; } = null!;

    public DateTime PublishedDate { get; set; }


    [ValidateNever]
    public virtual GoalType GoalType { get; set; } = null!;
}

StrawberryHub/Controllers/ArticlesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using StrawberryHub.Models;
using StrawberryHub.Services;
using System.Net.Http.Json;
using System.Text.Json;
using Microsoft.AspNetCore.Mvc.Infrastructure;
using Microsoft.Identity.Client;
using System.Net.Http.Headers;
using System.Drawing.Imaging;
using System.Drawing;
using System.IO;
using System.Net.Http;
using Microsoft.AspNetCore.Http;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.Formats.Png;
using SixLabors.ImageSharp.Processing;
using SixLabors.ImageSharp.PixelFormats;
using Microsoft.CodeAnalysis.Elfie.Diagnostics;
using System.Text.Json.Serialization;

namespace StrawberryHub.Controllers
{
    public class ArticlesController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment _env;
        private readonly string chatGptApiKey = "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";
        private const string ImageBufferKey = "ImageBuffer";

        public ArticlesController(AppDbContext context, IWebHostEnvironment env)
        {
            _context = context;
            _env = env;
        }

        private byte[] GetImageBuffer()
        {
            return HttpContext.Session.Get(ImageBufferKey)!;
        }

        private void SetImageBuffer(byte[] buffer)
        {
            HttpContext.Session.Set(ImageBufferKey, buffer);
        }

        // GET: Articles
        public async Task<IActionResult> Index()
        {
            var articles = _context.StrawberryArticle
                .Include(a => a.GoalType)
                .Include(a => a.StrawberryUser) // Assuming there's a property named User in StrawberryArticle representing the user who created the article
                .ToListAsync();
            return View(await articles);
        }

        // GET: Articles/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.StrawberryArticle == null)
            {
                return NotFound();
            }

            var article = await _context.StrawberryArticle
                .Include(a => a.GoalType)
                .Include(a => a.StrawberryUser)
                .FirstOrDefaultAsync(m => m.ArticleId == id);
            if (article == null)
            {
                return NotFound();
            }

            return View(article);
        }

        // GET: Articles/ArticleDetail/5
        public async Task<IActionResult> ArticleDetail(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var article = await _context.StrawberryArticle
                .Include(a => a.GoalType)
                .Include(a => a.StrawberryUser)
                .Include(a => a.StrawberryLike)
                .Include(a => a.StrawberryComment)
                .FirstOrDefaultAsync(m => m.ArticleId == id);
            if (article == null)
            {
                return NotFound();
            }

            var usernameClaim = HttpContext.User.FindFirst(ClaimTypes.Name);

            if (usernameClaim == null)
            {
                return BadRequest("Username claim not found");
            }

            var username = usernameClaim.Value;

            // Fetch the user from the database, including their preferences
            var user = _context.StrawberryUser.Include(u => u.Goal).FirstOrDefault(u => u.Username == username);

            if (user == null)
            {
                return NotFound("User not found");
            }

            // Check if the current user has liked this article
            var isLiked = article.StrawberryLike.Any(l => l.UserId == user.UserId);

            // Pass the like status to the view using ViewBag
            ViewBag.user = user.UserId;

            return View(article); // Assuming you have an "ArticleDetail.cshtml" view
        }

        // GET: Articles/Create
        public IActionResult Create()
        {
            ViewData["GoalTypeId"] = new SelectList(_context.StrawberryGoalType, "GoalTypeId", "Type");
            return View();
        }

        // POST: Articles/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ArticleId,GoalTypeId,Title,ArticleContent,PublishedDate,Photo,Picture,UserId")] StrawberryArticle article, IFormFile photo)
        {
            ModelState.Remove("Picture");     // No Need to Validate "Picture" - derived from "Photo".
            ModelState.Remove("UserId");
            ModelState.Remove("PublishDate");
            if (ModelState.IsValid)
            {
                var userIdClaim = HttpContext.User.FindFirst(ClaimTypes.Name);
                int userId = 0;
                if (userIdClaim != null)
                {
                    string username = userIdClaim.Value; // Extract the value of the claim
                    userId = await _context.StrawberryUser
                        .Where(u => u.Username == username)
                        .Select(u => u.UserId)
                        .FirstOrDefaultAsync();

                    // Now userId contains the UserId of the user with the specified username
                }

                    string picfilename = DoPhotoUpload(article.Photo);
                    article.Picture = picfilename.EscQuote();
                    article.UserId = userId; // Assign the retrieved user id to the article
                    article.PublishedDate = DateTime.Now;
                    _context.Add(article);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                
            }
            ViewData["GoalTypeId"] = new SelectList(_context.StrawberryGoalType, "GoalTypeId", "GoalTypeId", article.GoalTypeId);
            return View(article);
        }

        // GET: Articles/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.StrawberryArticle == null)
            {
                return NotFound();
            }

            var article = await _context.StrawberryArticle.FindAsync(id);
            if (article == null)
            {
                return NotFound();
            }
            ViewData["GoalTypeId"] = new SelectList(_context.StrawberryGoalType, "GoalTypeId", "Type", article.GoalTypeId);

            return View(article);
        }

        // POST: Articles/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ArticleId,GoalTypeId,Title,ArticleContent,PublishedDate,Photo,Picture,UserId")] StrawberryArticle article, IFormFile photo)
        {
            ModelState.Remove("Photo");       // No Need to Validate "Photo"
            ModelState.Remove("UserId");
            if (id != article.ArticleId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (photo != null)
                    {
                        string picfilename = DoPhotoUpload(photo);
                        article.Picture = picfilename.EscQuote();
                    }
                    article.PublishedDate = DateTime.Now;
                    _context.Update(article);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ArticleExists(article.ArticleId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["GoalTypeId"] = new SelectList(_context.StrawberryGoalType, "GoalTypeId", "GoalTypeId", article.GoalTypeId);
            return View(article);
        }

        // GET: Articles/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.StrawberryArticle == null)
            {
                return NotFound();
            }

            var article = await _context.StrawberryArticle
                .Include(a => a.GoalType)
                .FirstOrDefaultAsync(m => m.ArticleId == id);
            if (article == null)
            {
                return NotFound();
            }

            return View(article);
        }

        // POST: Articles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.StrawberryArticle == null)
            {
                return Problem("Entity set 'AppDbContext.Article'  is null.");
            }
            var article = await _context.StrawberryArticle.FindAsync(id);
            if (article != null)
            {
                string photoFile = article.Picture;
                string fullpath = Path.Combine(_env.WebRootPath, "photos/" + photoFile);
                System.IO.File.Delete(fullpath);

                _context.StrawberryArticle.Remove(article);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));

StrawberryHub/Views/Articles/AdminArticle.cshtml
@model List<StrawberryArticle>
<!DOCTYPE html>
<html lang="en">

<head>

	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta http-equiv="x-ua-compatible" content="ie=edge">

	<title>Strawberry Articles</title>
	<style>
		/* This will set the color of the item title and categories in light mode */
		body .item_title, body .item_categories {
			color: black;
		}

		/* This will set the color of the item title and categories in dark mode */
		body.dark-mode .item_title, body.dark-mode .item_categories {
			color: black;
		}
	</style>

</head>


<body>
		<!-- backtotop - start -->
		<div class="backtotop">
			<a href="#" class="scroll">
				Back to top
			</a>
		</div>
		<!-- backtotop - end -->
		<!-- header_section - start
		================================================== -->
		
		<!-- main body - start
		================================================== -->
		<main>

			<!-- breadcrumb_section - start
			================================================== -->
			<section class="breadcrumb_section">
				<div class="container">
					<h1 class="page_title text-white">
						<span class="d-block">Admin </span>
						<span class="d-block">Article</span>
					</h1>
					<p class="mb-0">
					These articles are generated from our creative admins to give daily post on maintaining stress management, mental wellness, and find new interest!
					</p>
				</div>
			</section>
			<!-- breadcrumb_section - end
			================================================== -->
			<!-- portfolio_section - start
			================================================== -->
			<section class="portfolio_section section_space pt-0">
				<div class="container">
					<div class="element_grid">
					@foreach (var article in Model)
					{
						string category = "";
						switch (article.GoalTypeId)
						{
							case 1:
								category = "stressManagement";
								break;
							case 2:
								category = "mentalWellness";
								break;
							case 3:
								category = "newHobbies";
								break;
								// Add more cases as needed
						}
						<div class="element-item category" data-category=@category>
							<a class="portfolio_fullimage_layout" href="@Url.Action("ArticleDetail", "Articles", new { id = article.ArticleId })">
								<img src="~/photos/@article.Picture" alt="image_not_found" style="max-width: 1260px; max-height: 900px;">
								<span class="item_content item-content">
									<strong class="item_title">@article.Title</strong>
									<small class="item_categories text-uppercase">@category</small>
								</span>
							</a>
						</div>
					}
					</div>
				</div>
			</section>
			<!-- portfolio_section - end
			================================================== -->

		</main>
		<!-- main body - end
		================================================== -->
		<!-- footer_section - start
		================================================== -->
		<footer class="footer_section">
			<div class="container">
			<h2 class="biggest_title text-center">One Berry at a Time</h2>
			</div>
		</footer>
		<!-- footer_section - end
		================================================== -->

</body>
</html>

StrawberryHub/Views/Articles/ArticlePage.cshtml
@model List<StrawberryArticle>
<!DOCTYPE html>
<html lang="en">

<head>

	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta http-equiv="x-ua-compatible" content="ie=edge">

	<title>Strawberry Articles</title>
	<style>
		/* This will set the color of the item title and categories in light mode */
		body .item_title, body .item_categories {
			color: black;
		}

		/* This will set the color of the item title and categories in dark mode */
		body.dark-mode .item_title, body.dark-mode .item_categories {
			color: black;
		}
	</style>

</head>


<body>
		<!-- backtotop - start -->
		<div class="backtotop">
			<a href="#" class="scroll">
				Back to top
			</a>
		</div>
		<!-- backtotop - end -->
		<!-- header_section - start
		================================================== -->
		
		<!-- main body - start
		================================================== -->
		<main>

			<!-- breadcrumb_section - start
			================================================== -->
			<section class="breadcrumb_section">
				<div class="container">
					<h1 class="page_title text-white">
						<span class="d-block">Our </span>
						<span class="d-block">Articles</span>
					</h1>
					<p class="mb-0">
						Strawberry User's Articles
					</p>
				</div>
			</section>
			<!-- breadcrumb_section - end
			================================================== -->
			<!-- portfolio_section - start
			================================================== -->
		<section class="portfolio_section section_space pt-0">
			<div class="container">
				<div class="filter_nav_wrap">
					@{
						var stressManagementCount = Model.Count(a => a.GoalTypeId == 1);
						var mentalWellnessCount = Model.Count(a => a.GoalTypeId == 2);
						var newHobbiesCount = Model.Count(a => a.GoalTypeId == 3);
						// Add more counts as needed
					}
					<h3 class="filter_nav_title text-uppercase">Filter by:</h3>
					<ul class="filter-btns-group button-group ul_li">
						<li><button class="button active" data-filter="*">All<sup>@Model.Count</sup></button></li>
						<li><button class="button" data-filter=".stress-management">Stress Management<sup>@stressManagementCount</sup></button></li>
						<li><button class="button" data-filter=".mental-wellness">Mental Wellness<sup>@mentalWellnessCount</sup></button></li>
						<li><button class="button" data-filter=".new-hobbies">New Interest<sup>@newHobbiesCount</sup></button></li>
					</ul>
				</div>
				<div class="element_grid">
					@foreach (var article in Model)
					{
						string category = "";
						switch (article.GoalTypeId)
						{
							case 1:
								category = "stress-management";
								break;
							case 2:
								category = "mental-wellness";
								break;
							case 3:
								category = "new-hobbies";
								break;
								// Add more cases as needed
						}
						<div class="element-item @category">
							<a class="portfolio_fullimage_layout" href="@Url.Action("ArticleDetail", "Articles", new { id = article.ArticleId })">
								<img src="~/photos/@article.Picture" alt="image_not_found" style="max-width: 1260px; max-height: 900px;">
								<span class="item_content item-content">
									<strong class="item_title">@article.Title</strong>
									<small class="item_categories text-uppercase">@category.Replace("-", " ")</small>
								</span>
							</a>
						</div>
					}
				</div>
			</div>
		</section>
			<!-- portfolio_section - end
			================================================== -->

		</main>
		<!-- main body - end
		================================================== -->
		<!-- footer_section - start
		================================================== -->
		<footer class="footer_section">
			<div class="container">

				<h2 class="biggest_title text-center">One Berry at a Time</h2>
			</div>
		</footer>
		<!-- footer_section - end
		================================================== -->

</body>
</html>

StrawberryHub/Views/Articles/Create.cshtml
@model StrawberryHub.Models.StrawberryArticle

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Article</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-controller="Articles" asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <!-- Add a hidden input field for UserId -->
            <input type="hidden" asp-for="UserId" />
            <div class="form-group">
                <label asp-for="GoalTypeId" class="control-label"></label>
                <select asp-for="GoalTypeId" class="form-control" asp-items="ViewBag.GoalTypeId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ArticleContent" class="control-label"></label>
                <textarea asp-for="ArticleContent" class="form-control textarea-content" rows="6" style="resize: vertical;"></textarea>
                <span asp-validation-for="ArticleContent" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label asp-for="PublishedDate" class="control-label"></label>
                <input asp-for="PublishedDate" class="form-control" />
                <span asp-validation-for="PublishedDate" class="text-danger"></span>
            </div>
            <div class="col-6 mb-3">
                <label asp-for="Photo">Add an image</label>
                <input asp-for="Photo" class="mb-3 form-control"
                       onchange="preview()">
                <div class="col-md-10">
                    <div class="mb-3 map_section">
                        <img class="d-none" style="max-height:600px;" id="frame" src="" />
                    </div>
                </div>
                <span asp-validation-for="Photo" class="text-danger"></span>
                
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>
<style>
    .textarea-content {
        white-space: pre-line;
    }
</style>
<script>
    function preview() {
        document.getElementById("frame").className = "d-md-block";
        frame.src = URL.createObjectURL(event.target.files[0]);
    }

    function clearImage() {
        document.getElementById('formFile').value = null;
        frame.src = "";
        document.getElementById("frame").className = "d-none d-md-block";
    }
</script>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

StrawberryHub/Views/Articles/EditArticle.cshtml
@model StrawberryHub.Models.StrawberryArticle

@{
    ViewData["Title"] = "Edit";
}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Edit Article</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
</head>

<body>
    <div class="container" style="font-family: 'Calibre';">
        <h1 class="page_title text-white">
            <span class="d-block">Edit </span>
            <span class="d-block">Your Article.</span>
        </h1>
    </div>
    <div class="container pt-1">
        <div class="row">
            <div class="col-md-6">
                <form asp-action="EditArticle" enctype="multipart/form-data" novalidate>
                    <input asp-for="Picture" hidden />
                    <input asp-for="UserId" hidden />
                    <input asp-for="PublishedDate" hidden />

                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="ArticleId" />
                    <div class="form-group">
                        <label asp-for="GoalTypeId" class="control-label">Goal Type</label>
                        <select asp-for="GoalTypeId" class="form-control" asp-items="ViewBag.GoalTypeId"></select>
                        <span asp-validation-for="GoalTypeId" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Title" class="control-label">Title</label>
                        <input asp-for="Title" class="form-control" />
                        <span asp-validation-for="Title" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ArticleContent" class="control-label">Article Content</label>
                        <textarea asp-for="ArticleContent" class="form-control" rows="6"></textarea>
                        <span asp-validation-for="ArticleContent" class="text-danger"></span>
                    </div>
                    <div class="col-6 mb-3">
                        <label asp-for="Photo">Edit image</label>
                        <input value="~/Photos/@Model.Picture" asp-for="Photo" class="mb-3 form-control" onchange="previewImage(this)" data-val="false">
                        <span asp-validation-for="Photo" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Save" class="btn btn-primary" />
                    </div>
                </form>
                <div>
                    <a asp-action="ArticleDetail" asp-controller="Articles" asp-route-id="@Model.ArticleId" class="btn btn-secondary">Back to Article</a>
                </div>
            </div>
                <div class="col-md-6">
                    <div class="mb-3">
                        <img id="ImgPhoto" src="~/Photos/@Model.Picture" class="img-fluid" alt="Article Image" />
                    </div>
                </div>
        </div>
    </div>

    @section Scripts {
        <script>
            function previewImage(input) {
                if (input.files && input.files[0]) {
                    var reader = new FileReader();
                    reader.onload = function (e) {
                        document.getElementById('ImgPhoto').src = e.target.result;
                    }
                    reader.readAsDataURL(input.files[0]);
                }
            }
        </script>
        @{
            await Html.RenderPartialAsync("_ValidationScriptsPartial");
        }
    }
</body>

</html>

StrawberryHub/Views/Articles/Mental.cshtml
@model List<StrawberryArticle>
<!DOCTYPE html>
<html lang="en">

<head>

	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta http-equiv="x-ua-compatible" content="ie=edge">

	<title>Strawberry Articles</title>
	<style>
		/* This will set the color of the item title and categories in light mode */
		body .item_title, body .item_categories {
			color: black;
		}

		/* This will set the color of the item title and categories in dark mode */
		body.dark-mode .item_title, body.dark-mode .item_categories {
			color: black;
		}
	</style>
</head>
<body>
		<!-- backtotop - start -->
		<div class="backtotop">
			<a href="#" class="scroll">
				Back to top
			</a>
		</div>
		<!-- backtotop - end -->
		<!-- header_section - start
		================================================== -->
		
		<!-- main body - start
		================================================== -->
		<main>

			<!-- breadcrumb_section - start
			================================================== -->
			<section class="breadcrumb_section">
				<div class="container">
					<h1 class="page_title text-white">
						<span class="d-block">Mental </span>
						<span class="d-block">Wellness</span>
					</h1>
					<p class="mb-0">
					Mental health awareness is growing among Singaporean youth, challenging traditional stigmas. Prioritizing mental wellness equips Gen Z with the resilience to thrive in Singapore's dynamic society, balancing cultural expectations with personal growth.
					</p>
				</div>
			</section>
			<!-- breadcrumb_section - end
			================================================== -->
			<!-- portfolio_section - start
			================================================== -->
			<section class="portfolio_section section_space pt-0">
				<div class="container">
					<div class="element_grid">
					@foreach (var article in Model)
					{
						string category = "";
						switch (article.GoalTypeId)
						{
							case 1:
								category = "stressManagement";
								break;
							case 2:
								category = "mentalWellness";
								break;
							case 3:
								category = "newHobbies";
								break;
								// Add more cases as needed
						}
						<div class="element-item category" data-category=@category>
							<a class="portfolio_fullimage_layout" href="@Url.Action("ArticleDetail", "Articles", new { id = article.ArticleId })">
								<img src="~/photos/@article.Picture" alt="image_not_found" style="max-width: 1260px; max-height: 900px;">
								<span class="item_content item-content">
									<strong class="item_title">@article.Title</strong>
									<small class="item_categories text-uppercase">@category</small>
								</span>
							</a>
						</div>
					}
					</div>
				</div>
			</section>
			<!-- portfolio_section - end
			================================================== -->

		</main>
		<!-- main body - end
		================================================== -->
		<!-- footer_section - start
		================================================== -->
		<footer class="footer_section">
			<div class="container">
			<h2 class="biggest_title text-center">One Berry at a Time</h2>
			</div>
		</footer>
		<!-- footer_section - end
		================================================== -->
</body>
</html>

StrawberryHub/Views/Articles/NewHobbies.cshtml
@model List<StrawberryArticle>
<!DOCTYPE html>
<html lang="en">

<head>

	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta http-equiv="x-ua-compatible" content="ie=edge">

	<title>Strawberry Articles</title>
	<style>
		/* This will set the color of the item title and categories in light mode */
		body .item_title, body .item_categories {
			color: black;
		}

		/* This will set the color of the item title and categories in dark mode */
		body.dark-mode .item_title, body.dark-mode .item_categories {
			color: black;
		}
	</style>
</head>
<body>
		<!-- backtotop - start -->
		<div class="backtotop">
			<a href="#" class="scroll">
				Back to top
			</a>
		</div>
		<!-- backtotop - end -->
		<!-- header_section - start
		================================================== -->
		
		<!-- main body - start
		================================================== -->
		<main>
			<!-- breadcrumb_section - start
			================================================== -->
			<section class="breadcrumb_section">
				<div class="container">
					<h1 class="page_title text-white">
						<span class="d-block">New </span>
						<span class="d-block">Hobbies</span>
					</h1>
					<p class="mb-0">
					Exploring new hobbies offers Gen Z Singaporeans a creative outlet and a break from the pressures of academic and career pursuits. Engaging in diverse interests can broaden perspectives, foster personal development, and create valuable connections in our multicultural city
					</p>
				</div>
			</section>
			<!-- breadcrumb_section - end
			================================================== -->
			<!-- portfolio_section - start
			================================================== -->
			<section class="portfolio_section section_space pt-0">
				<div class="container">
					<div class="element_grid">
					@foreach (var article in Model)
					{
						string category = "";
						switch (article.GoalTypeId)
						{
							case 1:
								category = "stressManagement";
								break;
							case 2:
								category = "mentalWellness";
								break;
							case 3:
								category = "newHobbies";
								break;
								// Add more cases as needed
						}
						<div class="element-item category" data-category=@category>
							<a class="portfolio_fullimage_layout" href="@Url.Action("ArticleDetail", "Articles", new { id = article.ArticleId })">
								<img src="~/photos/@article.Picture" alt="image_not_found" style="max-width: 1260px; max-height: 900px;">
								<span class="item_content item-content">
									<strong class="item_title">@article.Title</strong>
									<small class="item_categories text-uppercase">@category</small>
								</span>
							</a>
						</div>
					}
					</div>
				</div>
			</section>
			<!-- portfolio_section - end
			================================================== -->

		</main>
		<!-- main body - end
		================================================== -->
		<!-- footer_section - start
		================================================== -->
		<footer class="footer_section">
			<div class="container">
			<h2 class="biggest_title text-center">One Berry at a Time</h2>
			</div>
		</footer>
		<!-- footer_section - end
		================================================== -->
</body>
</html>